### ISSUE TITLE
V5 checklist

### ISSUE THREAD

**Issue by mikegoatly** [mikegoatly/lifti#71]
A quick braindump of the bits that will need to be tidied up before V5 can be released:

- [x] Add documentation for the concept of DynamicFields
- [x] Add documentation for new ObjectTokenizationBuilder methods for registering dynamic field readers
- [x] Update documentation for binary serializer to mention how fields can be re-mapped and constraints of changing the index definition when deserializing an existing index
- [x] Update documentation for LIFTI binary serialized format
